Facebook update; Readme better example;Chrome option
blackcapz/spammer pull request #12
Opened 2019-01-26 18:19 UTC by italojs

# README
## Easy documentation
I had dificult to understand what this project do, so i improve the readme to be more easy to know what this project do.

## Incomplete example
In the JSON request example don't had the `type` fields, it's throw an error when the Facebook strategy will decide between group or feed post type

# Code
## Facebook page out of date
I guess the Facebook update the facebook group post HTML because don't exist an `button.touchable` element or attribute(of some element) and it was throwing an exeption, so i update the element search by `div._4g34._6ber._5i2i._52we` (same of the FEED)

## Chrome option
The chromium that puppeteer install by default don't was working in my machine, so I need install some google chrome and set the binary path to puppeteer, so I added this option in the AbstractInterface.js file

2019-01-30 14:26 UTC, IgorHalfeld requested changes

2019-01-30 14:26 UTC, IgorHalfeld commented on README.md
> +Welcome to the easiest way to spam social networks. <br>
On markdown, two `spaces` make break line :D
Can you change the `<br>` to two spaces?

2019-01-30 14:26 UTC, IgorHalfeld commented on README.md
> +    { "id": "<group_id>",
Can you fix this indentation?

2019-01-30 14:26 UTC, IgorHalfeld commented on lib/AbstractInterface.js
> +if (process.env.PUPPETEER_EXECUTABLE_PATH)
This is really nice haha

2019-02-03 01:22 UTC, IgorHalfeld commented on README.md
> +    { "id": "<group_id>",
![image](https://user-images.githubusercontent.com/9022134/52171272-32ca7f80-2741-11e9-830b-6e586a373abd.png)

Still without correct indentation haha

2019-02-03 01:23 UTC, IgorHalfeld requested changes
Can you fix the README?

2019-02-03 13:02 UTC, italojs commented on README.md
> +    { "id": "<group_id>",
WTF? in my vs code it's perfect.

2019-02-03 13:03 UTC, italojs commented on README.md
> +    { "id": "<group_id>",
ok, it was an bizarre blank character that put a big space in the line

2019-02-03 18:42 UTC, IgorHalfeld approved these changes

2019-02-03 18:42 UTC, merged

2019-02-03 18:42 UTC, IgorHalfeld commented
Merged!